version: '3.3'
services:
  crawltricks:
    build: ./crawler
    environment:
     - REDIS_URL=redis://redis:6379
    command: -d ${DEPTH} -u ${URL}
    depends_on:
      - redis
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

  redis:
    image: redis:alpine
    ports:
      - "6379"
    volumes:
      - db-data:/data
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

volumes:
  db-data:
